### PR TITLE
Rename default branch of digitalmarketplace-bad-words

### PR DESCRIPTION
**Pull request by bjgill**
https://trello.com/c/DrVWMkcZ/2169-rename-default-branches-on-our-repos-from-master-to-main

### CODE REVIEW

**Comment by daniele-occhipinti** [comment]
Am I missing something or the [repo](https://github.com/alphagov/digitalmarketplace-bad-words) still uses `master` rather than `main`?

**Comment by daniele-occhipinti** [comment]
Does it mean you are ready to rename the branch on the other repo as soon as this is merged?

**Comment by bjgill** [comment]
I'm following the process in the linked Trello ticket. Once this PR is approved, I'll rename the branch and then merge this PR

**Comment by daniele-occhipinti** [comment]
Ah, OK, makes sense. Sorry, I missed that.

**Review by daniele-occhipinti — APPROVED** [review]
LGTM

**Comment by bjgill** [comment]
Ah, yes. It's one of very many, so I've possibly been a bit light on explanation here because it's all in the Trello ticket.

**Comment by daniele-occhipinti** [comment]
> Ah, yes. It's one of very many, so I've possibly been a bit light on explanation here because it's all in the Trello ticket.

No problem. Makes perfect sense.

**Pull request merged**
