### PR TITLE
Update Nginx AMI for #171

### PR DESCRIPTION
**Pull request by robyoung**
I forgot to add it to the pull request.

### CODE REVIEW

**Comment by TheDoubleK** [comment]
Where do you get the AMI reference number from? PR looks good, but I have no idea if it's the right number or not.

**Comment by allait** [comment]
:+1:

**Comment by robyoung** [comment]
@TheDoubleK I built the AMI using the [packer command in the README](https://github.com/alphagov/digitalmarketplace-aws#creating-amis-with-packer).  At the end of the process it gives you an AMI ID that can be used.

**Comment by allait** [comment]
@TheDoubleK you can find the AMIs in AWS Console > EC2 > Images > AMIs. Right now all images are created on the development AWS account.

**Comment by TheDoubleK** [comment]
Ah, OK yes should have read the manual...

**Pull request merged**
