### PR TITLE
add splunk service to apps

### PR DESCRIPTION
**Pull request by gidsg**
https://trello.com/c/yJeKtmkj/201-2-setup-splunk-on-our-apps-for-log-aggregation-timebox-2-days
add splunk service to apps. This is as-per https://github.com/alphagov/tech-ops/blob/master/cyber-security/components/csls-splunk-broker/docs/user-guide.md#bind-a-splunk-service-to-your-apps-using-an-app-manifest

### CODE REVIEW

**Comment by lfdebrux** [comment]
I think this is going to add splunk as a service to all apps in all spaces? Is that what we want right now?

**Comment by gidsg** [comment]
@lfdebrux I think so. My plan was to re-release all apps in Preview first so I can see it is working as expected before rolling out further. Although there is a small risk with this strategy that it may be inadvertently put into production by one of the apps deploying.

**Comment by lfdebrux** [comment]
> @lfdebrux I think so. My plan was to re-release all apps in Preview first so I can see it is working as expected before rolling out further. Although there is a small risk with this strategy that it may be inadvertently put into production by one of the apps deploying.

I think we might need some time testing Splunk in preview before we decide whether/how we want to use it in all spaces, so we should probably keep it just to preview for now if that's alright.

**Comment by gidsg** [comment]
> we should probably keep it just to preview 

@lfdebrux OK I have made this change in 9c4d5b0 and tested using `make generate-manifest`. 
Note as this adds some complexity to these files, we should aim to revert this and move to common as soon as we are comfortable rolling out Splunk more widely.

**Pull request merged**
