### PR TITLE
Enforce formatting on terraform files

### PR DESCRIPTION
**Pull request by samuelhwilliams**
## Summary
Start enforcing consistent formatting of Terraform configuration files through
Travis with a new `Makefile` step that runs `terraform fmt` on Pull Requests.
Also applies an initial sweep of re-formatting, which is mostly about aligning
variable values with correct spacing.

## Ticket
https://trello.com/c/ubqlb6pm/412-enforce-terraform-code-style

### CODE REVIEW

**Comment by risicle** [comment]
That does look like an *extremely* annoying format to edit in.

**Comment by risicle** [comment]
(though the test does pass for me & work on my setup)

**Comment by samuelhwilliams** [comment]
Why does it look annoying? You can basically edit it however you want and then just run the formatter.

Although honestly I prefer editing files like this and manually aligning the things /shrug

**Comment by risicle** [comment]
Does your space bar tend to wear out early? Personally I like editing content and not whitespace. "Oh look I've just made this key longer than any of the other keys in its paragraph, guess I'm going to be shifting the equals sign five to the right on all these lines too" - and then you end up with buckets of diff spam cluttering up your PRs and your `git blame`.

Is there even a choice over formatting settings? Because otherwise this is an academic discussion.

**Comment by samuelhwilliams** [comment]
This appears to be the standard format, which is what GOV.UK/PaaS use, so I think for cross-GDS consistency we'd just keep this.

**Comment by risicle** [comment]
fair enough

**Comment by samuelhwilliams** [comment]
FYI If you don't want to edit in the format this enforces, you can just do whatever you want and then run `terraform fmt -write=true -diff=true -list=true terraform` and it will fix everything for you. I will add this as a makefile step under `make terraformat-apply`

**Pull request merged**
