### PR TITLE
digitalmarketplace not digitalmarketplaces

### PR DESCRIPTION
**Pull request by lfdebrux**

### CODE REVIEW

**Comment by katstevens** [comment]
I thought we'd decided not to do this?

**Comment by lfdebrux** [comment]
> I thought we'd decided not to do this?

Ah, I thought we had just agreed to not worry about merging buckets/log groups

**Comment by benvand** [comment]
@katstevens @lfdebrux 
We can go either way, but maybe we should do it actually. Then we can move the logs from the badly named buckets into the proper buckets and delete the log groups. The logs will still exist just not in cloudwatch.

That way we don't need to keep track of duplicate buckets (either in or out of terraform (both would be a bit rubbish))

**Comment by benvand** [comment]
I'll approve pending comment from @katstevens

**Comment by katstevens** [comment]
Yep, that sounds sensible to me!

**Comment by lfdebrux** [comment]
Terraform has been applied and logs in buckets migrated

**Pull request merged**
