### PR TITLE
Upgrade instances to Amazon Linux 2014.09 v1.2.0

### PR DESCRIPTION
**Pull request by ajlanghorn**
Upgrade Digital Marketplace instances running in Elastic Beanstalk to Amazon Linux 2014.09 v1.2.0.

### CODE REVIEW

**Comment by robyoung** [comment]
How have these been tested?

**Comment by ajlanghorn** [comment]
They haven't been yet, @robyoung. That was the reason these haven't yet been merged.

I don't know how you do your testing, other than I suppose bringing up new Beanstalk instances.

**Comment by robyoung** [comment]
I think that would be it. We have some smoke tests but they haven't been wired up yet. I would think that i we can deploy an app to the new instance type and the smoke tests pass then it's probably going to be ok.

**Comment by TheDoubleK** [comment]
As soon as we have URLs for the deployed apps we can easily point the smoke tests at them to run - configurable in the Jenkins job.

**Comment by allait** [comment]
I've tested this in preview and it seems to be working with admin-frontend and api.
We had problems with deployment when moving from 1.0.9 to 1.1.0 and it appears to be ok with 1.2.0, so I'm :+1: to merge.

**Comment by ajlanghorn** [comment]
\o/

**Pull request merged**
