### PR TITLE
[TAKE 2] app environment variables: use ugly "if" statement to switch these to  the .apps.internal addresses for preview only

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/H53K45It

This is a re-attempt at https://github.com/alphagov/digitalmarketplace-aws/pull/508 which actually includes the final fix it needed to work.

### CODE REVIEW

**Comment by lfdebrux** [comment]
I can't see any difference between this and #508, have I misunderstood something?

**Comment by risicle** [comment]
Ahhh it's certainly subtle, but #508 feeds `DM_DATA_API_URL` to the router app but this one feeds `DM_API_URL` to it instead.

**Comment by risicle** [comment]
Oh actually that's interesting... the previous merge *wasn't* using the wrong env name... wonder what did it then...

**Comment by risicle** [comment]
Ok I'm going to merge this simply so I can take a better look at the running instance if/when it's going wrong rather than immediately panicking and reverting.

**Pull request merged**
