### PR TITLE
Remove Hosted Graphite configuration

### PR DESCRIPTION
**Pull request by lfdebrux**
We're no longer using Hosted Graphite, so I think these files are no longer needed.

We might want to keep around some code for pushing Grafana dashboards for our new metrics system, but my understanding was that we can't use our existing solution?

Thoughts welcome.

### CODE REVIEW

**Comment by katstevens** [comment]
I have a question - where are we defining the new Grafana dashboards?

**Comment by lfdebrux** [comment]
> I have a question - where are we defining the config for the new Grafana dashboards?

Currently it's not stored anywhere. We can manually export/import each dashboard by copy-pasting the JSON text https://grafana-paas.cloudapps.digital/d/B3XEtGPik/dm-overview?editview=dashboard_json&refresh=5m&orgId=1&panelId=&fullscreen=&edit=

**Comment by katstevens** [comment]
OK... Can we replace the `grafana/dm-apps.json` we're deleting here with that config, even if it's just temporary and we have to manually c&p it in, just so that we have it in version control somewhere? We can probably call it something else to make it clear it's not the old one.

**Comment by lfdebrux** [comment]
> OK... Can we replace the `grafana/dm-apps.json` we're deleting here with that config, even if it's just temporary and we have to manually c&p it in, just so that we have it in version control somewhere? We can probably call it something else to make it clear it's not the old one.

I've added these in a separate commit.

**Pull request merged**
