### PR TITLE
use python 3.9

### PR DESCRIPTION
**Pull request by gidsg**
https://trello.com/c/PqMIVIGW/13-upgrade-apps-to-python-36-38

Similar to https://github.com/alphagov/digitalmarketplace-scripts/pull/679 we are upgrading python in our non-deployable apps first to reduce risk.

### CODE REVIEW

**Review by bjgill — APPROVED** [review]
Looks good. Am I right in thinking that this only ever gets run by humans, so we don't need to worry about Jenkins/etc.?

**Comment by bjgill** [comment]
To merge this, it looks as if you'll need to remove some expected checks. I think you've got permissions to do so, but shout if not and I can.

**Comment by gidsg** [comment]
> Am I right in thinking that this only ever gets run by humans, so we don't need to worry about Jenkins/etc.?

Good point on further investigation, it seems like some scripts in this repo are run by Jenkins, for example https://github.com/alphagov/digitalmarketplace-aws/blob/main/scripts/generate-paas-manifest.py so I have converted this PR to a draft for now.

**Comment by gidsg** [comment]
Closing this as some of the scripts run on Jenkins which is still on Python 3.6

**Pull request closed without merging**
