### PR TITLE
default.nix: bump terraform to 0.11.3

### PR DESCRIPTION
**Pull request by risicle**
Please people, stop blindly bumping your terraform versions. This is getting tiring. Can we settle on 0.11.2 for a while maybe?

### CODE REVIEW

**Comment by TheDoubleK** [comment]
Are we 100% sure that there isn't someone who already has 0.11.3 installed, which will make 0.11.2 redundant as soon as they do something on the 2nd line rota?

The `terraform/README.md` currently says "install the latest version", so if we're going to pin it at 0.11.2 for a while we should probably update that (weirdly nested) README to reflect that at the same time.

**Comment by Wynndow** [comment]
Be worth pinning it in the terraform too: https://www.terraform.io/docs/configuration/terraform.html

**Comment by samuelhwilliams** [comment]
Probably easier to pin it at the current latest, 0.11.3, in case as @TheDoubleK says, someone's already got that installed.

**Comment by Wynndow** [comment]
Yeah, I've got 0.11.3, and that's what was used on the main account on Monday.

**Comment by risicle** [comment]
Well let's be real - it's `default.nix`, this is just for me...

**Comment by risicle** [comment]
I've upgraded it to 0.11.3, but I don't really get the point of pinning it in terraform's config...

**Comment by Wynndow** [comment]
It should prevent someone from accidentally advancing the Terraform version for everyone else?

**Comment by risicle** [comment]
Oh I see, it can specify a *maximum* version, too.

Issue I can see with this though - for the rest of you is it actually easy to have an "arbitrary" terraform version installed? What do you use? Homebrew?

**Comment by Wynndow** [comment]
Yeah, homebrew

**Pull request merged**
